### Recuperar todas las partidas de tictactoe
GET http://localhost:3000/tictactoe

### Recuperar partida de tictactoe con un id
GET http://localhost:3000/tictactoe/c3efbb2c-7234-414e-8354-cedfeea78d63

### Crear una nueva partida
POST http://localhost:3000/tictactoe
Content-Type: application/json

{
    "user": "o",
    "type": "online"
}

###Actualizar una partida en curso
PATCH http://localhost:3000/tictactoe/c3efbb2c-7234-414e-8354-cedfeea78d63
Content-Type: application/json

{
    "board": [
      ["X", "", ""],
      ["", "O", ""],
      ["", "", ""]
    ],

    "moves": [
        {"player": "rojano", "row": 0, "col": 0},
        {"player": "IA", "row": 0, "col": 0}
    ],

    "winner": ""
}